package com.ganesh.fleetdispatch.events;

public enum FleetEventType {
    KAFKA_TEST,
    DRIVER_REGISTERED,
    DRIVER_LOCATION_UPDATED,
    DRIVER_OFFLINE,
    DRIVER_RECONNECTED,
    ORDER_CREATED,
    ORDER_ASSIGNED,
    ORDER_PICKED_UP,
    ORDER_COMPLETED,
    ORDER_CANCELLED,
    ORDER_RECOVERY_STARTED,
    ORDER_RECOVERY_ASSIGNED,
    ORDER_RECOVERY_RETRY
}
